### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by keyoni**
Updated Readme with Documentation written by @BorisMarin8004 and Libraries

### CODE REVIEW

**Comment by BorisMarin8004** [comment]
I think the Retrofit docs at the end of readme are from before rxjava

**Comment by keyoni** [comment]
> I think the Retrofit docs at the end of readme are from before rxjava It should use these docs: #56

Got it, I'll make the change now!

**Review by BorisMarin8004 — APPROVED** [review]
Great 👍

**Review by bKondo — APPROVED** [review]

**Comment by parw8649** [comment]
Good work!

**Review by parw8649 — APPROVED** [review]

**Pull request merged**
